{% set name = "napari-brainbow-diagnose" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-brainbow-diagnose-{{ version }}.tar.gz
  sha256: d7f126ca4c3abc47cc088a8fd6146129a708766a651214c47007f96bc56433cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - magicgui
    - matplotlib
    - napari
    - numpy
    - pooch
    - python >=3.8,<3.11
    - qtpy
    - scikit-image

test:
  imports:
    - napari_brainbow_diagnose
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LaboratoryOpticsBiosciences/napari-brainbow-diagnose
  summary: Visualize and Diagnose brainbow dataset in color space.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
